---
root: true

plugins:
  - jest
  - babel

env:
  browser: true
  es2021: true
  jest: true

extends:
  - airbnb-base
  - plugin:jest/recommended

parserOptions:
  ecmaVersion: latest
rules:
  no-console: 0
  import/extensions: 0
